repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-case-conflict # Check for files with names that would conflict on a case-insensitive filesystem
      - id: check-merge-conflict # Check for files that contain merge conflict strings (e.g. <<<<<<<, =======, >>>>>>>)
      - id: check-toml # Check TOML files for syntax errors
      - id: check-yaml # Check YAML files for syntax errors
      - id: end-of-file-fixer # Makes sure files end in a newline and only a newline
      - id: trailing-whitespace # delete whitespace at the end of a line

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.6.3"
    hooks:
      - id: ruff # Run ruff to lint your code
        args: [--exit-non-zero-on-fix]
      - id: ruff-format # Run ruff to format your code

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.3"
    hooks:
      - id: prettier # prettier is a formatter for JavaScript, TypeScript, CSS, Markdown, JSON, GraphQL, YAML, HTML, Vue, and Angular
